### PR TITLE
update website after move

### PR DESCRIPTION
**Pull request by lnnrtwttkhn**
we cloned from previous course (<https://github.com/lnnrtwttkhn/version-control-course-uhh-ws23>) at v1.0.

this PR cleans up to adapt the website to the new course

### CODE REVIEW

**Comment by lnnrtwttkhn** [comment]
@konradpa would you please take this over?

please go through all website contents (also the individual sessions and slides etc.) and update all content related to the previous session. in doing so, please make extensive use of `_variables.yml`. this is a great opportunity now to setup the website materials in a way they can be easily adapted to future course formats.

thanks!

**Comment by konradpa** [comment]
> @konradpa would you please take this over?
> 
> please go through all website contents (also the individual sessions and slides etc.) and update all content related to the previous session. in doing so, please make extensive use of `_variables.yml`. this is a great opportunity now to setup the website materials in a way they can be easily adapted to future course formats.
> 
> thanks!

I continued updating the website. Few Questions:
- Is it possible to use YAML variables in a YAML File? (for the dates in the schedule)
- Is it possible to use YAML variables in the date section of a quarto presentation? (gives me an error)
- What is the Tag of the course in Stine this year?  I added it as variable and put question marks a placeholder for now.

**Comment by lnnrtwttkhn** [comment]
thanks @konradpa, very useful changes!

> Is it possible to use YAML variables in a YAML File? (for the dates in the schedule)

> Is it possible to use YAML variables in the date section of a quarto presentation? (gives me an error)

not entirely sure what you mean, but yes, in principle you can use the variables in `_variables.yml` file in the YAML header of a `.qmd` file. for some metadata in the YAML header, this does not work, but I haven't fully understood why this is the case. as you mentioned dates, I also found dates to be tricky to implement with variables.

> What is the Tag of the course in Stine this year? I added it as variable and put question marks a placeholder for now.

added in 1778f4119dc125e290029ebbccb911fea23d556a

**Comment by lnnrtwttkhn** [comment]
Overall, this looks very good now IMO. I think before we tackle the content-related ideas in #1 further, we could merge this PR, bring the website online and then continue implementing #1.

**Comment by konradpa** [comment]
> Overall, this looks very good now IMO. I think before we tackle the content-related ideas in #1 further, we could merge this PR, bring the website online and then continue implementing #1.

Looks good to me as well.

**Pull request merged**
